language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t abby95/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abby95/docker-react npm run test -- --coverage --watchAll=false
